const FLAGS: Record<string, string> = {
  'England':       '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Scotland':      '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales':         '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Germany':       '🇩🇪',
  'France':        '🇫🇷',
  'Spain':         '🇪🇸',
  'Portugal':      '🇵🇹',
  'Netherlands':   '🇳🇱',
  'Belgium':       '🇧🇪',
  'Italy':         '🇮🇹',
  'Croatia':       '🇭🇷',
  'Switzerland':   '🇨🇭',
  'Austria':       '🇦🇹',
  'Denmark':       '🇩🇰',
  'Sweden':        '🇸🇪',
  'Norway':        '🇳🇴',
  'Poland':        '🇵🇱',
  'Serbia':        '🇷🇸',
  'Hungary':       '🇭🇺',
  'Turkey':        '🇹🇷',
  'Brazil':        '🇧🇷',
  'Argentina':     '🇦🇷',
  'Uruguay':       '🇺🇾',
  'Colombia':      '🇨🇴',
  'Chile':         '🇨🇱',
  'Ecuador':       '🇪🇨',
  'Peru':          '🇵🇪',
  'Paraguay':      '🇵🇾',
  'Venezuela':     '🇻🇪',
  'Bolivia':       '🇧🇴',
  'United States': '🇺🇸',
  'Mexico':        '🇲🇽',
  'Canada':        '🇨🇦',
  'Panama':        '🇵🇦',
  'Costa Rica':    '🇨🇷',
  'Jamaica':       '🇯🇲',
  'Honduras':      '🇭🇳',
  'Haiti':         '🇭🇹',
  'El Salvador':   '🇸🇻',
  'Morocco':       '🇲🇦',
  'Senegal':       '🇸🇳',
  'Nigeria':       '🇳🇬',
  'Ghana':         '🇬🇭',
  'Cameroon':      '🇨🇲',
  'Egypt':         '🇪🇬',
  'South Africa':  '🇿🇦',
  'DR Congo':      '🇨🇩',
  'Algeria':       '🇩🇿',
  'Tunisia':       '🇹🇳',
  'Ivory Coast':   '🇨🇮',
  'Mali':          '🇲🇱',
  'Japan':         '🇯🇵',
  'South Korea':   '🇰🇷',
  'Australia':     '🇦🇺',
  'New Zealand':   '🇳🇿',
  'Saudi Arabia':  '🇸🇦',
  'Iran':          '🇮🇷',
  'Qatar':         '🇶🇦',
  'China':         '🇨🇳',
  'Indonesia':     '🇮🇩',
  'Uzbekistan':    '🇺🇿',
}

export function getFlag(team: string): string {
  return FLAGS[team] ?? '🏳️'
}
