const FLAGS: Record<string, string> = {
  England: '🏴',
  Scotland: '🏴',
  Wales: '🏴',
  Germany: '🇩🇪',
  France: '🇫🇷',
  Spain: '🇪🇸',
  Portugal: '🇵🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Italy: '🇮🇹',
  Croatia: '🇭🇷',
  Switzerland: '🇨🇭',
  Austria: '🇦🇹',
  Denmark: '🇩🇰',
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Poland: '🇵🇱',
  Brazil: '🇧🇷',
  Argentina: '🇦🇷',
  Uruguay: '🇺🇾',
  Ecuador: '🇪🇨',
  'United States': '🇺🇸',
  USA: '🇺🇸',
  Mexico: '🇲🇽',
  Canada: '🇨🇦',
  Panama: '🇵🇦',
  Haiti: '🇭🇹',
  Morocco: '🇲🇦',
  Senegal: '🇸🇳',
  'South Africa': '🇿🇦',
  'DR Congo': '🇨🇩',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Australia: '🇦🇺',
  'New Zealand': '🇳🇿',
}

export function getFlag(team: string): string {
  return FLAGS[team] ?? '🏳️'
}
